### ISSUE TITLE
Unable to connect to postgres without postGIS installed

### ISSUE THREAD

**Issue by DanielHeath** [pdeffendol/spatial_adapter#37] opened 2012-09-09 23:20 UTC
My app connects to multiple databases via activerecord, some of which have postGIS and some do not.

When I use an AR class which connects to a db without postGIS, 
I get a PG::Error (relation "geometry_columns" does not exist)
at `spatial_adapter/postgresql.rb:216` in column_spatial_info.

I've been getting past this by including the following module in my AR objects, but would prefer a real fix.

`module SupressSpatialCalculation # Since we dont have postGIS installed on this DB
  def column_spatial_info(column_name)
    {}
  end
end
`

Would it make sense to handle this error within the adapter? (and maybe even disable the extra GIS features for that class when it's encountered)

**Comment by pdeffendol** [comment] 2012-09-27 16:50
Duplicate of #15.

Note I'm no longer making new releases of spatial_adapter - I'd recommend using the RGeo library instead.

**Closed as completed by pdeffendol** 2012-09-27 16:50 UTC
